name: Voteik
main: de.xzise.bukkit.voteik.Voteik
description: Voteik allows you to vote.
version: 0.1.0
authors:
    - 'xZise'
commands:    
    vote:
        description: Vote commands.
        usage: /<command> help - Show the help of vote-commands.
        aliases: [v]